In [26]:
import pandas as pd
df = pd.read_html('http://jsjustweb.jihsun.com.tw/z/zc/zcq/zcq_1101.djhtm')
df2 = df[2][0:]
df2.columns = df2.iloc[0]
df2.reindex(df2.index.drop(1))

,期別,2021.1Q,2020.4Q,2020.3Q,2020.2Q,2020.1Q,2019.4Q,2019.3Q,2019.2Q
0,期別,2021.1Q,2020.4Q,2020.3Q,2020.2Q,2020.1Q,2019.4Q,2019.3Q,2019.2Q
2,營業收入毛額,22038,32119,29809,30464,21976,35221,30838,31367
3,營業收入淨額,22038,32119,29809,30464,21976,35221,30838,31367
4,銷貨成本,16513,21745,19255,19584,16195,24842,21119,22044
5,營業成本,16513,21745,19255,19584,16195,24842,21119,22044
...,...,...,...,...,...,...,...,...,...
102,庫藏股數－母公司,12,12,12,12,8,8,8,8
103,庫藏股數－子公司持有母公司股票或其他,0,0,0,0,0,0,0,0
104,庫藏股數（母持及子持母）,12,12,12,12,8,8,8,8
105,稅前息前淨利,5273,9608,11151,11320,5260,9314,9493,9886
106,稅前息前折舊前淨利,7095,11489,12954,13103,7059,11136,11459,11685